/**
 * THE CORPUS ON DISK — where a regenerated kit specification lives, and how it is trusted.
 *
 * The embedded snapshot (`src/artifacts/`) is what makes this adapter work with no setup: five
 * files compiled into the bundle, no path to get wrong, no `existsSync` that can be false
 * (`src/artifacts/index.ts:19-29`). This file adds the second half — a way for
 * `fe --parse-ui-kit eds` to produce a NEWER five and have them used — without giving back the
 * failure mode the embedding removed.
 *
 * ── THE PRECEDENCE RULE, AND ITS ONE INVARIANT ──────────────────────────────────────────────
 *
 * A run uses the on-disk corpus when it is COMPLETE and VALID, and the embedded one otherwise.
 * The invariant underneath is that **there is no third outcome**: this module has no throwing
 * path, so an unreadable, truncated, hand-edited or half-written corpus directory costs the user
 * a warning line and nothing else. An analyzer that refuses to run because a cache is corrupt is
 * strictly worse than one that ignores the cache, and the cache here is a cache — every byte of
 * it can be regenerated by re-running one command.
 *
 * Four states, and each is answered differently on purpose:
 *
 *  - NOTHING THERE → embedded, silently. The overwhelmingly common case; a user who never ran
 *    `--parse-ui-kit` must not be told about a feature they did not use.
 *  - ALL FIVE, ALL VALID → the on-disk five, and the notice says so with its date and sha.
 *  - SOME THERE, SOME MISSING → embedded, with a warning naming what is missing. This is a
 *    broken corpus rather than an absent one — an interrupted write, or a deleted file — and
 *    silently falling back would hide a regeneration the user believes succeeded.
 *  - PRESENT BUT INVALID → embedded, with a warning naming THE BAD FILE. Naming it is the whole
 *    value of the message: "the corpus is invalid" sends someone to five files.
 *
 * ── WHY THE WARNINGS ARE CODES AND NOT SENTENCES ────────────────────────────────────────────
 *
 * This package has no user-facing strings and no dependency on `@smart-tools/fe-cli-kit`. A
 * {@link CorpusWarning} carries a `reason` and a `file`, and the feature package turns it into
 * ru+en (`packages/fe-project-report/src/strings.ts`). That is the arrangement B1 fixed for
 * `fe-source` and the reason it gave — "NO user-facing strings … Localized ru+en wording is the
 * feature package's job, built from `code`" — and following it keeps the localization TOTAL BY
 * TYPE: adding a reason here breaks the build in the file that renders them.
 *
 * ── WHY THE ON-DISK FILES ARE VALIDATED AND THE EMBEDDED ONES ARE NOT ───────────────────────
 *
 * Not an inconsistency — the opposite. `domain/artifacts.ts:1-24` argues that re-parsing the
 * embedded four megabytes would "validate the build against itself", because those files are
 * compiled in from source committed beside them and a test already pins their shape. A corpus
 * directory is the exact inverse: a path on a user's machine that a user can edit, that a
 * previous version of this tool may have written, and that nothing has checked. So it gets the
 * full Zod parse, every time, before a single rule sees it.
 */
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join, resolve } from "node:path";

import type {
  ComponentsArtifact,
  KitA11yArtifact,
  KitIconsArtifact,
  KitSignaturesArtifact,
  TokensArtifact,
} from "./domain/artifacts.ts";
import { componentsArtifactSchema } from "./extract/domain/components.ts";
import { kitA11yArtifactSchema } from "./extract/domain/kit-a11y.ts";
import { kitIconsArtifactSchema } from "./extract/domain/kit-icons.ts";
import { kitSignaturesArtifactSchema } from "./extract/domain/kit-knowledge.ts";
import { tokensArtifactSchema } from "./extract/domain/tokens.ts";
import { CORPUS_MEMBERS, type CorpusMember, type KitCorpus } from "./extract/pipeline.ts";
import { corpusStampSchema, type CorpusStamp } from "./extract/provenance.ts";

/** The environment variable that moves the whole kits tree — the brief's `FE_KITS_DIR`. */
export const KITS_DIR_ENV = "FE_KITS_DIR";

/** `~/.fe/kits` unless {@link KITS_DIR_ENV} says otherwise. */
export const kitsRoot = (
  env: Readonly<Record<string, string | undefined>> = process.env,
): string => {
  const override = env[KITS_DIR_ENV];
  // Resolved to an ABSOLUTE path: the result card lists absolute paths (E2b contract), so a
  // relative `FE_KITS_DIR` must not leak through as-is.
  return override !== undefined && override !== ""
    ? resolve(override)
    : join(homedir(), ".fe", "kits");
};

/** `<kitsRoot>/<kit>` — where one design system's five files live. */
export const corpusDir = (
  kit: string,
  env: Readonly<Record<string, string | undefined>> = process.env,
): string => join(kitsRoot(env), kit);

/** The absolute path of one corpus member. */
export const corpusFile = (
  kit: string,
  member: CorpusMember,
  env: Readonly<Record<string, string | undefined>> = process.env,
): string => join(corpusDir(kit, env), `${member}.json`);

/** Why an on-disk corpus was not used. `file` is absolute, so the message can be acted on. */
export interface CorpusWarning {
  readonly reason: "incomplete" | "invalid";
  readonly file: string;
  /** The first schema issue, for `invalid`. Unlocalized and diagnostic, never the whole message. */
  readonly detail?: string | undefined;
}

/** Which snapshot a run is measuring against, and — when it is the disk's — where it came from. */
export type CorpusProvenance =
  | { readonly kind: "embedded"; readonly version: string | null }
  | {
      readonly kind: "updated";
      readonly version: string | null;
      readonly commit: string | null;
      readonly extractedAt: string;
    };

export interface LoadedCorpus {
  readonly corpus: KitCorpus | null;
  readonly provenance: CorpusProvenance | null;
  readonly warnings: readonly CorpusWarning[];
}

/** One member's schema. Written as a lookup so {@link CORPUS_MEMBERS} stays the single list. */
const SCHEMAS = {
  tokens: tokensArtifactSchema,
  components: componentsArtifactSchema,
  "kit-a11y": kitA11yArtifactSchema,
  "kit-icons": kitIconsArtifactSchema,
  "kit-signatures": kitSignaturesArtifactSchema,
} as const;

/** A parsed member plus the stamp the writer put on it. */
interface ReadMember {
  readonly artifact: unknown;
  readonly stamp: CorpusStamp;
}

/**
 * Read and validate one member. Returns a warning instead of throwing, always.
 *
 * A missing file and a malformed one are DIFFERENT answers: the first is `incomplete` (the
 * corpus is not all there), the second is `invalid` (it is there and wrong). Collapsing them
 * would make "you never ran the command" and "your corpus is corrupt" print the same sentence.
 */
const readMember = async (
  kit: string,
  member: CorpusMember,
  env: Readonly<Record<string, string | undefined>>,
): Promise<ReadMember | CorpusWarning> => {
  const file = corpusFile(kit, member, env);

  let text: string;
  try {
    text = await readFile(file, "utf8");
  } catch {
    return { reason: "incomplete", file };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch (cause) {
    return {
      reason: "invalid",
      file,
      detail: cause instanceof Error ? cause.message : String(cause),
    };
  }

  // The stamp is read off a COPY of `meta` and then removed, so what the schema validates — and
  // what the rules eventually see — is exactly the artifact the extractor produced. A corpus
  // written by this tool always has one; a file without it was not written by `--parse-ui-kit`,
  // and treating it as a corpus member would mean trusting an unknown provenance.
  const stamped = takeStamp(parsed);
  if (stamped === null) {
    return {
      reason: "invalid",
      file,
      detail: `missing meta.corpus — this file was not written by "fe --parse-ui-kit ${kit}"`,
    };
  }
  if (stamped.stamp.kit !== kit) {
    return {
      reason: "invalid",
      file,
      detail: `meta.corpus.kit is "${stamped.stamp.kit}" but this is the "${kit}" corpus`,
    };
  }

  const result = SCHEMAS[member].safeParse(stamped.artifact);
  if (!result.success) {
    const issue = result.error.issues[0];
    return {
      reason: "invalid",
      file,
      detail:
        issue === undefined
          ? "failed schema validation"
          : `${issue.path.length > 0 ? issue.path.join(".") : "<root>"}: ${issue.message}`,
    };
  }

  // THE VALUE ON DISK, not `result.data`, and the distinction is not pedantic — it was found by
  // a failing round-trip test. Zod REWRITES the object it validates: keys come back in the
  // SCHEMA's declaration order rather than the file's, and `z.object`'s default strip mode drops
  // anything the schema does not name. Both would be silent corruption of a file this tool
  // wrote: the reordering breaks the guarantee that a corpus is byte-for-byte the artifact its
  // extractor produced, and the stripping would delete a field added by a NEWER version of this
  // tool, turning a forward-compatible corpus into a lossy one.
  //
  // So the schema is used for the one thing it is for — deciding whether the file is usable —
  // and the bytes that were on disk are what the rules get.
  return { artifact: stamped.artifact, stamp: stamped.stamp };
};

/**
 * Split `meta.corpus` off a parsed artifact, returning the artifact without it.
 *
 * Total and non-mutating: the input is a freshly parsed JSON value nobody else holds, but
 * rebuilding rather than deleting keeps this function safe to call on anything.
 */
const takeStamp = (value: unknown): { artifact: unknown; stamp: CorpusStamp } | null => {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return null;
  const record = value as Record<string, unknown>;
  const meta = record["meta"];
  if (typeof meta !== "object" || meta === null || Array.isArray(meta)) return null;

  const metaRecord = meta as Record<string, unknown>;
  const parsed = corpusStampSchema.safeParse(metaRecord["corpus"]);
  if (!parsed.success) return null;

  const { corpus: _removed, ...rest } = metaRecord;
  return { artifact: { ...record, meta: rest }, stamp: parsed.data };
};

const isWarning = (value: ReadMember | CorpusWarning): value is CorpusWarning => "reason" in value;

export interface LoadCorpusOptions {
  /** The design system id — the directory name under the kits root. */
  readonly kit: string;
  /** Replaces `process.env`, so a test can point `FE_KITS_DIR` somewhere without mutating it. */
  readonly env?: Readonly<Record<string, string | undefined>> | undefined;
}

/**
 * Load an on-disk corpus, or explain why the embedded one is being used instead.
 *
 * NEVER THROWS, and never rejects. Every failure is a `warning` and a `null` corpus — see the
 * file header for why that is the contract rather than a convenience.
 *
 * All five members are read even after the first failure, deliberately: a user whose corpus has
 * three bad files should learn that from one run, not from three.
 */
export const loadCorpus = async (options: LoadCorpusOptions): Promise<LoadedCorpus> => {
  const env = options.env ?? process.env;
  const results = await Promise.all(
    CORPUS_MEMBERS.map(
      async (member) => [member, await readMember(options.kit, member, env)] as const,
    ),
  );

  const warnings = results.map(([, result]) => result).filter(isWarning);

  // Nothing there at all is not a broken corpus, it is the default state of a fresh machine.
  if (
    warnings.length === CORPUS_MEMBERS.length &&
    warnings.every((w) => w.reason === "incomplete")
  ) {
    return { corpus: null, provenance: null, warnings: [] };
  }
  if (warnings.length > 0) return { corpus: null, provenance: null, warnings };

  const members = results.map(([member, result]) => [member, result as ReadMember] as const);
  const corpus = Object.fromEntries(
    members.map(([member, { artifact }]) => [member, artifact]),
  ) as unknown as KitCorpus;

  // The stamp of `tokens.json` is the corpus's stamp. The five are written in one pass from one
  // extraction, so they agree by construction; picking one rather than reconciling five is the
  // honest encoding of that, and a mismatch would mean the directory was assembled by hand —
  // which `meta.corpus.kit` already refuses.
  const stamp = members[0]?.[1].stamp;

  return {
    corpus,
    provenance:
      stamp === undefined
        ? null
        : {
            kind: "updated",
            version: stamp.version,
            commit: stamp.commit,
            extractedAt: stamp.extractedAt,
          },
    warnings: [],
  };
};

export type {
  ComponentsArtifact,
  KitA11yArtifact,
  KitIconsArtifact,
  KitSignaturesArtifact,
  TokensArtifact,
};

/* --------------------------------------------------------------------------------------- *
 * WRITING — the other half of the same contract, kept in the same file on purpose.
 *
 * The reader's four states are only meaningful if the writer is the thing that produces state
 * two, and the two halves share the member list, the path builder and the stamp shape. Splitting
 * them would create the classic drift: a writer that emits `meta.corpus` in one shape and a
 * reader that expects another, discovered by a user rather than by the compiler.
 * --------------------------------------------------------------------------------------- */

/**
 * Write a corpus, stamped, and return the absolute path of every file written.
 *
 * ATOMICITY, AND HOW MUCH OF IT THERE IS. Each file is written to a sibling `.tmp` name and
 * renamed into place, so no reader can observe a half-written JSON document — `rename` within a
 * directory is atomic on every filesystem this runs on. The DIRECTORY as a whole is not
 * transactional: a crash between the third and fourth rename leaves a corpus that is complete
 * for three members and stale for two. That state is exactly the reader's `incomplete`/mixed
 * case, which falls back to the embedded snapshot with a warning naming the file — so the
 * unhandled half of the atomicity story is handled on the other side, which is the reason the
 * reader treats a partial directory as broken rather than as absent.
 *
 * The files are pretty-printed with a trailing newline, matching the hackathon's own
 * `writeJsonFile` (`ds-analyzer/src/shared/fs.ts`), because a corpus is something a human is
 * expected to open when a report says something surprising.
 */
export const writeCorpus = async (options: WriteCorpusOptions): Promise<readonly string[]> => {
  const env = options.env ?? process.env;
  const directory = corpusDir(options.kit, env);
  await mkdir(directory, { recursive: true });

  const written: string[] = [];
  for (const member of CORPUS_MEMBERS) {
    const file = corpusFile(options.kit, member, env);
    const temporary = `${file}.tmp`;
    await writeFile(
      temporary,
      `${JSON.stringify(stamp(options.corpus[member], options.stamp), null, 2)}\n`,
      "utf8",
    );
    await rename(temporary, file);
    written.push(file);
  }
  return written;
};

export interface WriteCorpusOptions {
  readonly kit: string;
  readonly corpus: KitCorpus;
  readonly stamp: CorpusStamp;
  readonly env?: Readonly<Record<string, string | undefined>> | undefined;
}

/**
 * The artifact with `meta.corpus` added — the exact inverse of {@link takeStamp}.
 *
 * `meta` is rebuilt rather than mutated, and the stamp goes LAST so a human opening the file
 * reads the kit's own metadata first and the provenance at the end of the block. Every field the
 * extractor put in `meta` survives untouched, which is what makes the round trip in
 * `tests/corpus.test.ts` — write, strip, compare against the extractor's output — an equality
 * rather than a subset check.
 */
const stamp = (artifact: unknown, corpus: CorpusStamp): unknown => {
  const record = artifact as Record<string, unknown>;
  const meta = record["meta"];
  const metaRecord = typeof meta === "object" && meta !== null && !Array.isArray(meta) ? meta : {};
  return { ...record, meta: { ...metaRecord, corpus } };
};
